# The theory and notations used in this file are documented in detail in the
# Bernstein bases algorithms Developper notes of the official documentation.

"""
    FEEC_space_definition_checks(::Val{D}, T, r, k, F, rotate_90; cart_prod=false)

Check if the argument define a valid Finite Element Exterior Calculus (FEEC) polynomial space,
as defined in the Periodic Table of the Finite Elements, ``\\mathrm{F}ᵣΛᵏ`` in dimension `D`.

The arguments are also described in [`FEEC_poly_basis`](@ref).
"""
function FEEC_space_definition_checks(
  ::Val{D},::Type{T},r::Integer,k::Integer,F::Symbol, rotate_90::Bool=false, DG_calc::Bool=false;
  cart_prod=false
) where {D,T}

  if cart_prod
    @check k in (0, D) "Basis for Cartesian product of polynomial space only possible for `k` = 0 or `D`, got k=$k and D=$D"
    @check T<:Number
  else
    @check T<:Real "T needs to be <:Real since represents the scalar type, got $T. If you want to define a Cartesian product FEEC basis, use `cart_prod=true`"
  end
  @check F in (:P⁻,:P,:Q⁻,:S) "F must be either :P⁻,:P,:Q⁻ or :S, got $F."
  @check k in 0:D "The form order k must be in 0:D, got k=$k and D=$D."
  @check r ≥ 0    "The polynomial order r must be positive, got $r."

  if DG_calc
    @notimplemented "A new MultiValue type and associated algebraic operations ∧/⋆/𝑑/δ need to be implemented to use form valued polynomials."
  elseif D>3 && ( 1 < k < D-1)
    @unreachable "Vector calculus proxy of differential form bases are only available for `k`=0,1,`D`-1 or `D`, got k=$k and D=$D."
  end

  if rotate_90 && !(!DG_calc && isone(k) && D==2)
    @warn """The `rotate_90` kwarg only makes sense for 2D vector proxied forms
              of degree 1, it will be ignored and may lead to errors.
              Got k=$k, D=$D for F=$F
          """
  end
  true
end

#############################
# BarycentricPΛIndices type #
#############################

# Do print some BarycentricPΛIndices generated by PΛ_bubbles(r,k,D) in REPL before
# reading this...

# All types and fields "XX" below should be understood as "Indices_For_XX"

# One bubble function:
#               ω_w  =      (  w,           α, α_id,           J,   sub_J_ids,  sup_α_ids )
const BubbleFunction = Tuple{Int, Vector{Int},  Int, Vector{Int}, Vector{Int}, Vector{Int}}

# One bubble space associated to the d-dimensional face F
# bubble_d_F =      (          F,    F_bubble_functions )
const Bubble = Tuple{Vector{Int}, Vector{BubbleFunction}}

"""
    struct BarycentricPΛIndices
      identity::UInt
      bubbles::Vector{Bubble}
      components::Vector{Tuple{ Int, Vector{Int}, Int}}
    end

For storing indices in `BarycentricP(m)ΛBasis`. The `bubbles` are generated by
[`PΛ_bubbles`](@ref) or [`PmΛ_bubbles`](@ref), the `components` by
[`_basis_forms_components`](@ref).
"""
struct BarycentricPΛIndices
  # An objectid is stored here to keep track of what's inside and perform a
  # sanity check when reusing the indices elsewhere:
  #     identity = objectid( (r,k,D,:P,false,false) )
  # for a PᵣΛᵏ(△ᴰ) basis indices with vector-proxied components and rotate_90=false.
  identity::UInt

  # bubble indices given by P(m)Λ_bubbles (can be filtered and renumbered to select subset of bubbles)
  # The BubbleFunction[1] "w" MUST be in increasing order when iterating over bubbles and bubble_functions
  bubbles::Vector{Bubble}

  # Indices for the components of a basis k-form or its vector calculus proxy,
  #                       (I_id,           I, sgnIcomp), see _basis_forms_components .
  components::Vector{Tuple{ Int, Vector{Int},      Int}}

  # Components "I" of the exterior derivative of a basis polynomial form
  # ext_deriv_components::Vector{Component}
end

function _check_PΛ_indices(r,k,D,F,DG_style, indices::BarycentricPΛIndices, rot_90)
  @check F ∈ (:P,:P⁻)
  # Changing one of those requires re-computing all fields of BarycentricPΛIndices,
  # otherwise wrong result or segfault due to @inbounds in evaluating functions
  # are expected
  @assert objectid( (r,k,D,F,DG_style,rot_90) ) == indices.identity

  @check begin
    ordered_bf_ids = [ bubfun[1] for bub in indices.bubbles for bubfun in bub[2] ]
    C = length(ordered_bf_ids)
    ordered_bf_ids == 1:C
  end "Invalid BarycentricPΛIndices: bubble functions are not numbered from 1 to length(b) in the bubble indices"

  @check begin
    unique_faces = Set()
    for bubble in indices.bubbles
      push!(unique_faces, sort(bubble[1]))
    end
    length(unique_faces) == length(indices.bubbles)
  end """
    Invalid BarycentricPΛIndices: all bubble functions to a face must be
    gathered in a unique Bubble, duplicated bubble faces were found in the given
    indices
  """
end

"""
    _last_bubble_function_index(ids::BarycentricPΛIndices)

The index of the last bubble function in `ids`, that is also the number of basis
polynomial defined by `ids`, and cardinal of the owning basis.
"""
function _last_bubble_function_index(ids::BarycentricPΛIndices)
  isempty(ids.bubbles) && return 0
  return ids.bubbles[end][2][end][1]
end

function Base.show(io::IO, ::MIME"text/plain", indices::BarycentricPΛIndices)
  if isempty(indices.bubbles)
    print(io,"Empty PΛ basis indices")
    return
  end

  α = indices.bubbles[1][2][1][2]
  J = indices.bubbles[1][2][1][4]
  I = indices.components[1][2]

  r = sum(α)+length(J)-length(I)
  k = length(I)
  D = length(α)-1
  is_Pm = r != sum(α)
  basis_str = "Pᵣ"* (is_Pm ? "⁻" : "") * "Λᵏ(△ᴰ) "
  println(io, basis_str, "basis indices, r=$r k=$k D=$D")

  println(io)
  println(io,"Basis polynomial components")
  println(io,"\tI_id\t I\t I_sgn")
  for (I_id, I, I_sgn) in indices.components
    println(io,"\t$I_id\t $(join(I))\t $I_sgn")
  end

  println(io)
  _print_bubble_table(io, indices, :AFW, nothing)
  println(io)
  println(io, basis_str, "basis indices, r=$r k=$k D=$D")
end

"""
    _print_bubble_table(out, indices, flavor, Ψ)

Print the column header and one row per bubble function of `indices`, the
common body of [`print_indices`](@ref) and of the `BarycentricPΛIndices`
`show` method.

`P⁻` index sets wedge `k`+1 barycentric differentials where `P` ones wedge
`k`, which is what tells the two apart here.

`Ψ` holds the direction form of each bubble function and is known only to a
`BarycentricPΛBasis`; pass `nothing` to leave that column empty.
"""
function _print_bubble_table(out::IO, indices::BarycentricPΛIndices, flavor::Symbol, Ψ)
  isempty(indices.bubbles) && return

  k = length(indices.components[1][2])
  is_Pm = length(indices.bubbles[1][2][1][4]) != k

  # :BMM indexes its direction form by a single vertex, which the rotating-basis
  # literature calls k, and its Whitney form by the pair the trimmed one calls e.
  J_title = flavor === :BMM && isone(k) ? (is_Pm ? "e" : "k") : "J"
  # :BMM scales a P⁻ basis function by the bare monomial λ^α instead of Bα.
  bare = is_Pm && flavor === :BMM

  form_title = is_Pm ? "sub_J_ids" : "Ψ"
  form(w, sub_J_ids) = is_Pm ? join(sub_J_ids,",") : (isnothing(Ψ) ? "" : "$(Ψ[w])")
  form_width = max(length(form_title),
                   maximum(length(form(bf[1], bf[5])) for (_, bfs) in indices.bubbles for bf in bfs)) + 2

  println(out,
    rpad("w",4), rpad("F",10), rpad(J_title,8), rpad("α",14),
    rpad(bare ? "λ^α" : "Bα(λ)",18), rpad(form_title,form_width), "α_id")

  for (F, bubble_functions) in indices.bubbles
    for (w, α, α_id, J, sub_J_ids) in bubble_functions
      mono = _monomial_string(α; coeff = bare ? 1 : multinomial(α...))
      println(out,
        rpad("$w",4), rpad(join(F,","),10), rpad(join(J,","),8),
        rpad("$(Tuple(α))",14), rpad(mono,18),
        rpad(form(w, sub_J_ids),form_width), α_id)
    end
  end
end


###########################################
# BarycentricPmΛBasis nD polynomial bases #
###########################################

"""
    BarycentricPmΛBasis{D,V,K} <: PolynomialBasis{D,V,Bernstein}

Finite Element Exterior Calculus polynomial basis for the spaces P⁻`ᵣ`Λ`ᵏ` on
`D`-dimensional simplices, but with polynomial forms explicitely transformed
into vectors using the standard equivalence with usual vector calculus defined
in terms of the hodge star operator ⋆ and the sharp map ♯, see
[`_basis_forms_components`](@ref) (the simplex is assumed Euclidean).

- `V` is `VectorValue{L,T}` where `L` is binomial(`D`,`k`),
- `K` is the polynomial order of the underlying scalar bernstein polynomial basis

The number of basis polynomials is binomial(`r`+`k`-1,`k`)*binomial(`D`+`r`,`D`-`k`) if no filtered bubble indices are given.

Reference: D.N. Arnold, R.S. Falk & R. Winther, Geometric decompositions and local bases for spaces of finite element differential forms, CMAME, 2009
"""
struct BarycentricPmΛBasis{D,V,K} <: PolynomialBasis{D,V,Bernstein}
  k::Int
  scalar_bernstein_basis::BernsteinBasisOnSimplex{D,Float64,K}
  # Family of exterior-k-products of barycentric differential dλʲ,
  # indexed by the k-faces J of the D-simplex, in the order of sorted_combinations(D+1,k)
  m::Vector{V}
  _indices::BarycentricPΛIndices
  flavor::Symbol

  function BarycentricPmΛBasis{D}(::Type{T}, r, k, vertices;
        DG_calc=false, indices=nothing, rotate_90=false, flavor=:AFW) where {D,T}

    @check flavor in (:AFW, :BMM)
    FEEC_space_definition_checks(Val(D), T, r, k, :P⁻, rotate_90, DG_calc)
    _simplex_vertices_checks(Val(D), vertices)

    indices = _generate_or_check_PmΛ_indices(r,k,D,DG_calc,indices,rotate_90)

    L = binomial(D,k) # Number of components of a basis form
    V = VectorValue{L,T} # To update once DG_calc is implemented

    b = BernsteinBasisOnSimplex{D}(Float64, r, vertices)
    K = get_order(b)
    LN = binomial(D+1,k) # Number of k-faces J of a D-dimensional tetrahedron
    m = Vector{V}(undef, LN)
    _compute_PmΛ_basis_coefficients!(m,Val(k),D,b,vertices,indices)

    if isone(L) && !DG_calc
      V = T
      m = collect(reinterpret(T, m))
    end

    new{D,V,K}(k,b,m,indices,flavor)
  end

  @doc """
      BarycentricPmΛBasis(b::BarycentricPmΛBasis, faces::Vector{Int}...)

  Create a new basis which is `b` restricted to the bubble spaces for F ∈ `faces`.
  The new basis shares internal fields data with `b`.
  """
  function BarycentricPmΛBasis(_b::BarycentricPmΛBasis{D,V,K}, faces::Vector{Int}...) where {D,V,K}
    # Notation: _old, new
    _indices = _b._indices
    _bubbles = _indices.bubbles
    bubbles = similar(_bubbles, length(faces))

    w = 1
    for (Fid, F) in enumerate(faces)
      F_id = findfirst(bub -> bub[1] == F, _bubbles)
      @assert !isnothing(F_id) "No bubble associated to face $F in the given basis"

      _F_bubfuns = _bubbles[F_id][2]
      F_bubfuns = similar(_F_bubfuns)
      for (i, _fun) in enumerate(_F_bubfuns)
        # re-use all α,J, etc... to minimise allocation, just change w
        F_bubfuns[i] = (w, _fun[2:end]...)
        w += 1
      end
      bubbles[Fid] = (F, F_bubfuns)
    end

    indices = BarycentricPΛIndices(_indices.identity, bubbles, _indices.components)
    # re-use m too
    new{D,V,K}(_b.k, _b.scalar_bernstein_basis, _b.m, indices, _b.flavor)
  end

  function BarycentricPmΛBasis{D,V,K}() where {D,V,K} # just for testvalue
    r = K
    indices = _generate_or_check_PmΛ_indices(r,0,0,false,nothing,false)
    B = BernsteinBasisOnSimplex{D,Float64,K}
    new{D,V,K}(0,testvalue(B),zeros(V,1),indices,:AFW)
  end
end

"""
    BarycentricPmΛBasis(::Val{D}, T, r, k; kwargs...)
    BarycentricPmΛBasis(::Val{D}, T, r, k, vertices; kwargs...)

Constructors for [`BarycentricPmΛBasis`](@ref) of scalar type `T`.
If `vertices` are specified, they must define a non-degenerate simplex, c.f. [`BernsteinBasisOnSimplex`](@ref).

The kwargs are the following:
- `indices::BarycentricPΛIndices = nothing`: may be provided to avoid allocations of new indices, or to select specific bubbles spaces,
- `DG_calc = false`: set to `true` to choose `k`-form valued polynomials instead of vector valued polynomials (not implemented yet),
- `rotate_90 = false`: In 2`D` for `k`=1, `true` to apply a 90° rotation of the vector proxied polynomials ((x,y) -> (-y,x)), needed for Raviart-Thomas/BDM.
"""
function BarycentricPmΛBasis(::Val{D},::Type{T},r,k; kwargs...) where {D,T}
  BarycentricPmΛBasis{D}(T,r,k; kwargs...)
end
function BarycentricPmΛBasis(::Val{D},::Type{T},r,k,vertices; kwargs...) where {D,T}
  BarycentricPmΛBasis{D}(T,r,k,vertices; kwargs...)
end

function BarycentricPmΛBasis{D}(::Type{T},r,k; kwargs...) where {D,T}
  Pt = Point{D,Float64}
  vertices = ntuple( j -> Pt( ntuple( i -> j==i+1, Val(D)) ), Val(D+1))
  BarycentricPmΛBasis{D}(T,r,k,vertices; kwargs...)
end

BarycentricPmΛBasis(::Val{D},::Type{T},r,k,::Nothing; kwargs...) where {D,T} = BarycentricPmΛBasis(Val(D),T,r,k; kwargs...)
BarycentricPmΛBasis{D}(::Type{T},r,k,::Nothing; kwargs...) where {D,T} = BarycentricPmΛBasis{D}(T,r,k; kwargs...)


#get_FEEC_poly_degree(b::BarycentricPmΛBasis) = b.r
#get_FEEC_form_degree(b::BarycentricPmΛBasis) = b.k
#get_FEEC_family(::BarycentricPmΛBasis) = :P⁻

Base.size(b::BarycentricPmΛBasis) = (_last_bubble_function_index(b._indices), )

function testvalue(::Type{BarycentricPmΛBasis{D,V,K}}) where {D,V,K}
  BarycentricPmΛBasis{D,V,K}()
end

##########################################
# BarycentricPΛBasis nD polynomial bases #
##########################################

"""
    BarycentricPΛBasis{D,V,K} <: PolynomialBasis{D,V,Bernstein}

Finite Element Exterior Calculus polynomial basis for the spaces P`ᵣ`Λ`ᵏ` on
`D`-dimensional simplices, but with polynomial forms explicitely transformed
into vectors using the standard equivalence with usual vector calculus defined
in terms of the hodge star operator ⋆ and the sharp map ♯, see
[`_basis_forms_components`](@ref) (the simplex is assumed Euclidean).

- `V` is `VectorValue{L,T}` where `L=binomial(D,k)`,
- `K` is the polynomial order of the underlying scalar bernstein polynomial basis

The number of basis polynomials is binomial(`r`+`k`,`k`)*binomial(`D`+`r`,`D`-`k`) if no custom bubble indices are given.

Reference: D.N. Arnold, R.S. Falk & R. Winther, Geometric decompositions and local bases for spaces of finite element differential forms, CMAME, 2009
"""
struct BarycentricPΛBasis{D,V,K} <: PolynomialBasis{D,V,Bernstein}
  k::Int
  scalar_bernstein_basis::BernsteinBasisOnSimplex{D,Float64,K}
  # Direction k-form of each basis polynomial
  Ψ::Vector{V}
  _indices::BarycentricPΛIndices
  flavor::Symbol

  function BarycentricPΛBasis{D}(::Type{T}, r, k, vertices;
        DG_calc=false, indices=nothing, rotate_90=false, flavor=:AFW) where {D,T}

    @check flavor in (:AFW, :BMM)
    FEEC_space_definition_checks(Val(D), T, r, k, :P⁻, rotate_90, DG_calc)
    _simplex_vertices_checks(Val(D), vertices)

    indices = _generate_or_check_PΛ_indices(r,k,D,DG_calc,indices,rotate_90)

    L = binomial(D,k) # Number of components of a basis form
    V = VectorValue{L,T} # To update once DG_calc is implemented
    C = _last_bubble_function_index(indices) # Cardinal of the basis

    b = BernsteinBasisOnSimplex{D}(Float64, r, vertices)
    K = get_order(b)
    Ψ = Vector{V}(undef, C)
    _compute_PΛ_basis_form_coefficient!(Ψ,r,k,Val(D),b,vertices,indices,flavor)

    if isone(L) && !DG_calc
      V = T
      Ψ = collect(reinterpret(T, Ψ))
    end

    new{D,V,K}(k,b,Ψ,indices,flavor)
  end

  @doc """
      BarycentricPΛBasis(b::BarycentricPΛBasis, faces::Vector{Int}...)

  Create a new basis which is `b` restricted to the bubble spaces for F ∈ `faces`.
  The faces are represented by some `Vector{Int}` of their vertices ids, like in
  [`BarycentricPΛIndices`](@ref).
  """
  function BarycentricPΛBasis(_b::BarycentricPΛBasis{D,V,K}, faces::Vector{Int}...) where {D,V,K}
    # Notation: _old, new
    _indices = _b._indices
    _bubbles = _indices.bubbles
    _Ψ = _b.Ψ

    bubbles = similar(_bubbles, length(faces))
    Ψ = similar(_Ψ) # of maximum possible size, trimmed below
    w = 1

    for (Fid, F) in enumerate(faces)
      F_id = findfirst(bub -> bub[1] == F, _bubbles)
      @assert !isnothing(F_id) "No bubble associated to face $F in the given basis"

      _F_bubfuns = _bubbles[F_id][2]
      F_bubfuns = similar(_F_bubfuns)
      for (i, _fun) in enumerate(_F_bubfuns)
        # re-use all α,J, etc... to minimise allocation, just change w
        (_w, _fun_ids...) = _fun
        F_bubfuns[i] = (w, _fun_ids...)
        Ψ[w] = _Ψ[_w]
        w += 1
      end
      bubbles[Fid] = (F, F_bubfuns)
    end

    resize!(Ψ, w-1)
    indices = BarycentricPΛIndices(_indices.identity, bubbles, _indices.components)
    new{D,V,K}(_b.k, _b.scalar_bernstein_basis, Ψ, indices, _b.flavor)
  end

  function BarycentricPΛBasis{D,V,K}() where {D,V,K} # Just for testvalue
    indices = _generate_or_check_PΛ_indices(K,0,0,false,nothing,false)
    B = BernsteinBasisOnSimplex{D,Float64,K}
    C = _last_bubble_function_index(indices)
    new{D,V,K}(0,testvalue(B),zeros(V,C),indices,:AFW)
  end
end

"""
    BarycentricPΛBasis(::Val{D}, T, r, k; kwargs...)
    BarycentricPΛBasis(::Val{D}, T, r, k, vertices; kwargs...)

Constructors for [`BarycentricPΛBasis`](@ref) of scalar type `T`.
If `vertices` are specified, they must define a non-degenerate simplex, c.f. [`BernsteinBasisOnSimplex`](@ref).

The kwargs are the following:
- `indices::BarycentricPΛIndices = nothing`: may be provided to avoid allocations of new indices, or to select specific bubbles spaces,
- `DG_calc = false`: set to `true` to choose `k`-form valued polynomials instead of vector valued polynomials (not implemented yet),
- `rotate_90 = false`: In 2`D` for `k`=1, `true` to apply a 90° rotation of the vector proxied polynomials ((x,y) -> (-y,x)), needed for Raviart-Thomas/BDM.
- `flavor = :AFW`: `:BMM` selects the alternative direction forms of [`_update_φ_αF!`](@ref), only defined for `k` ≤ 1.
"""
function BarycentricPΛBasis(::Val{D},::Type{T},r,k; kwargs...) where {D,T}
  BarycentricPΛBasis{D}(T,r,k; kwargs...)
end
function BarycentricPΛBasis(::Val{D},::Type{T},r,k,vertices; kwargs...) where {D,T}
  BarycentricPΛBasis{D}(T,r,k,vertices; kwargs...)
end

function BarycentricPΛBasis{D}(::Type{T},r,k; kwargs...) where {D,T}
  Pt = Point{D,Float64}
  vertices = ntuple( j -> Pt( ntuple( i -> j==i+1, Val(D)) ), Val(D+1))
  BarycentricPΛBasis{D}(T,r,k,vertices; kwargs...)
end

BarycentricPΛBasis(::Val{D},::Type{T},r,k,::Nothing; kwargs...) where {D,T} = BarycentricPΛBasis(Val(D),T,r,k; kwargs...)
BarycentricPΛBasis{D}(::Type{T},r,k,::Nothing; kwargs...) where {D,T} = BarycentricPΛBasis{D}(T,r,k; kwargs...)

#get_FEEC_poly_degree(b::BarycentricPΛBasis) = b.r
#get_FEEC_form_degree(b::BarycentricPΛBasis) = b.k
#get_FEEC_family(::BarycentricPΛBasis) = :P

Base.size(b::BarycentricPΛBasis) = (_last_bubble_function_index(b._indices), )

function testvalue(::Type{BarycentricPΛBasis{D,V,K}}) where {D,V,K}
  BarycentricPΛBasis{D,V,K}()
end

##########################
# Common Implementation  #
##########################

const _BaryPΛBasis{D} = Union{BarycentricPmΛBasis{D}, BarycentricPΛBasis{D}}

"""
    get_bubbles(b::BarycentricPmΛBasis)
    get_bubbles(b::BarycentricPΛBasis)

Get the iterator over the bubble spaces in the geometric decomposition of `b`,
typically generated by [`PmΛ_bubbles`](@ref) or [`PΛ_bubbles`](@ref).

They can be vizualized using [`print_indices(b)`](@ref print_indices).
"""
get_bubbles(b::_BaryPΛBasis) = b._indices.bubbles
get_order(b::_BaryPΛBasis) = get_order(b.scalar_bernstein_basis)
get_orders(b::_BaryPΛBasis{D}) where D = tfill(get_order(b), Val(D))

"""
    print_indices(b::BarycentricPmΛBasis, out=stdout)
    print_indices(b::BarycentricPΛBasis,  out=stdout)

Prints the indices of `b` in a user friendly format into `out`, one row per
basis polynomial. It is also what `show` displays.

The scalar factor column is `Bα(λ)`, except for `PmΛ` with `flavor=:BMM` where
it is the bare monomial `λ^α`.

With `flavor=:BMM` and `k`=1, `J` holds a single vertex for `PΛ` and is titled
`k`, and a vertex pair for `PmΛ` and is titled `e`.
"""
function print_indices(b::BarycentricPmΛBasis{D}, out::IO=stdout) where D
  println(out, "BarycentricPmΛBasis{D=$D, r=$(get_order(b)), k=$(b.k), $(b.flavor)}: dim = $(length(b))")
  _print_bubble_table(out, b._indices, b.flavor, nothing)
end

function print_indices(b::BarycentricPΛBasis{D}, out::IO=stdout) where D
  println(out, "BarycentricPΛBasis{D=$D, r=$(get_order(b)), k=$(b.k), $(b.flavor)}: dim = $(length(b))")
  _print_bubble_table(out, b._indices, b.flavor, b.Ψ)
end

Base.show(io::IO, b::_BaryPΛBasis) = print_indices(b, io)

"""
    print_forms(b::BarycentricPΛBasis,  out::IO=stdout)
    print_forms(b::BarycentricPmΛBasis, out::IO=stdout)

Print each basis function of `b` as an ambient barycentric differential form,
in terms of dλ¹,…,dλ^{D+1} — the frame the φ and ϕ formulas are stated in —
with symbolic polynomial coefficients.

For a `BarycentricPΛBasis` the form is `Bα(λ)` times the wedge of the direction
1-forms [`_update_φ_αF!`](@ref) indexed by `J`, and the polynomial degree must be
at least 1. For a `BarycentricPmΛBasis` it is the Whitney form `φ^J` scaled by
`Bα(λ)` for `flavor=:AFW`, by the bare monomial `λ^α` for `flavor=:BMM`.

Requires the Symbolics package to be loaded: the methods are provided by the
GridapSymbolicsExt package extension.
"""
function print_forms end

const _sup_digits = ("⁰","¹","²","³","⁴","⁵","⁶","⁷","⁸","⁹")
_sup_str(i::Int) = join(_sup_digits[d+1] for d in reverse(digits(i)))

# Plain-string monomial coeff·(λ¹)^α₁⋯(λᴺ)^α_N, e.g. "3(λ¹)²λ²".
function _monomial_string(α; coeff=1)
  s = isone(coeff) ? "" : string(coeff)
  for (i, αi) in enumerate(α)
    αi == 0 && continue
    s *= αi > 1 ? "(λ" * _sup_str(i) * ")" * _sup_str(αi) : "λ" * _sup_str(i)
  end
  isempty(s) ? "1" : s
end

_get_x_to_λ(b::_BaryPΛBasis) = b.scalar_bernstein_basis.x_to_λ

function _return_cache(b::_BaryPΛBasis,x,::Type{G},::Val{N_deriv}) where {G,N_deriv}
  T = eltype(G)
  np = length(x)
  ndof = length(b)
  ndof_bernstein = length(b.scalar_bernstein_basis)

  r = CachedArray(zeros(G,(np,ndof)))
  # Cache for all scalar nD-Bernstein polynomials Bα
  cB = CachedVector(zeros(T,ndof_bernstein))
  # Cache for derivatives of Bα (∇Bα or HBα)
  if N_deriv > 0
    DB = T
    xi = testitem(x)
    for _ in 1:N_deriv
      DB = gradient_type(DB,xi)
    end
    # Cache for N_deriv's derivatives all of scalar nD-Bernstein polynomials
    t = (( nothing for _ in 2:N_deriv)..., CachedArray(zeros(DB,(1,ndof_bernstein))))
    s = MArray{Tuple{size(DB)...},T}(undef)
  else
    t = ()
    s = nothing
  end
  (r, s, cB, t...)
end

function _setsize!(b::_BaryPΛBasis, np, ω, t...)
  ndof = length(b)
  ndof_bernstein = length(b.scalar_bernstein_basis)
  setsize!(ω,(np,ndof))
  setsize!(t[1],(ndof_bernstein,)) # this is cB
  if length(t) > 1
    setsize!(t[end],(1,ndof_bernstein)) # this is ∇B or HB
  end
end

function _get_parameters(b::_BaryPΛBasis)
  r = get_order(b)
  return Val(r)
end

"""
    _basis_forms_components(D,k,DG_style,rotate_90)

If `DG_style==true`, return the triples (`I_id`, `I`, 1) for each D-dimensional
k-form components dxᴵ = dxᴵ¹ ∧ dxᴵ² ∧ ... ∧ dxᴵᵏ where `I` is a combination of
1:`D` and `I_id = combination_index(I)`. The triples are ordered like in
[`sorted_combinations`](@ref) (`I_id` increasing).

If `DG_style`==false, the indices are changed to implement the vector proxy of
the differential forms ω defined by:
- ω♯    if `k` = 0 or 1
- (⋆ω)♯ if `k` = `D`-1 or `D` and `k`>1
where ⋆ is the hodge star operator and ♯ the sharp map.

The triples become (`I_proxy_id`, `I`, `I_proxy_sgn`) with the same `I` (and in
the same order), such that the components of the vector proxy v of a `k`-form ω are

    v[I_proxy_id] = I_proxy_sgn * ω[I_id]

If `k` ∈ {0,1,`D`}, the proxy is trivial. If `k`=`D`-1, ♯ reverses the
components order and ⋆ adds signs 1, -1, 1, -1 ...

If `rotate_90` is `true` and `k` is `1`, the (⋆ω)♯ proxy is applied instead of ω♯.
"""
function _basis_forms_components(D,k,DG_style,rot_90)
  components = Vector{Tuple{ Int, Vector{Int}, Int}}(undef, binomial(D,k))
  for (I_id, I) in enumerate(sorted_combinations(D,k))
    # The rotation for 2D Raviart-Thomas/BDM is actually considering k to be D-1
    # rather than 1, that is applying ⋆.
    if DG_style || iszero(k) || isone(k) && !rot_90
      components[I_id] = (I_id, I, 1)
    else # if k == D, I = [1:D] and this is just (1, [], 1) (but that works)
      Icomp = _complement(I, D)
      Istar_id = combination_index(Icomp, D)
      Istar_sgn = _combination_sign(I)
      components[I_id] = (Istar_id, I, Istar_sgn)
    end
  end
  components
end


######################################
# BarycentricPmΛBasis Implementation #
######################################

function _generate_or_check_PmΛ_indices(r,k,D,DG_style,::Nothing,rot_90)
  identity = objectid( (r,k,D,:P⁻,DG_style,rot_90) )
  bubbles = PmΛ_bubbles(r,k,D)
  components = _basis_forms_components(D,k,DG_style,rot_90)
  return BarycentricPΛIndices(identity,bubbles,components)
end

function _generate_or_check_PmΛ_indices(r,k,D,DG_style,indices::BarycentricPΛIndices,rot_90)
  _check_PΛ_indices(r,k,D,:P⁻,DG_style,indices,rot_90)
  return indices
end

function _PmΛ_F_bubble_functions(r,k,D,F,w)
  N = D + 1
  ids = BubbleFunction[]
  for α in bernstein_terms(r-1,D)
    sup_α_ids = _sup_multi_indices(α)
    for J in sorted_combinations(N,k+1)
      sub_J_ids = _sub_combinations_ids(J, N)
      j = _minimum_or_one(J)-1
      if issetequal(_support(α) ∪ J, F) && all(α[1:j] .== 0)
        w += 1
        α_id = bernstein_term_id(α)
        push!(ids, (w, α, α_id, J, sub_J_ids, sup_α_ids))
      end
    end
  end
  ids
end

"""
    PmΛ_bubbles(r,k,D)

Generates the indices caracterizing the basis function of `BarycentricPmΛBasis`,
described in the Bernstein bases algorithm Developper notes of the official
documentation, and are used as follows:

    for (F, bubble_functions) in PmΛ_bubbles(r,k,D)
      for (w, α, α_id, J, sub_J_ids, sup_α_ids) in bubble_functions
        # ...
      end
    end
"""
function PmΛ_bubbles(r,k,D)
  w=0
  bubbles = Bubble[]
  for d in k:D
    for F in sorted_combinations(D+1, d+1; right_to_left=true)
      bubble_functions = _PmΛ_F_bubble_functions(r,k,D,F,w)
      isempty(bubble_functions) && continue
      push!(bubbles, (F, bubble_functions))
      w += length(bubble_functions)
    end
  end
  @check w == binomial(r+k-1,k)*binomial(D+r,D-k)
  bubbles
end

"""
    _compute_PmΛ_basis_coefficients!(m, Val(k), D, b, vertices, indices)

Set the `binomial(D+1, k)` exterior-`k`-products of the barycentric
differentials dλʲ is place in `m`.
"""
function _compute_PmΛ_basis_coefficients!(m,::Val{k},D,b,vertices,indices) where k
  V = eltype(m)
  M = transpose(b.x_to_λ[:,2:end])
  m_J = Mutable(V)(undef)
  @inbounds for (J_id, J) in enumerate(sorted_combinations(D+1,k))
    for (I_id, I, I_sgn) in indices.components
      m_J[I_id] = I_sgn * _minor(M,I,J,Val(k))
    end
    m[J_id] = m_J
  end
  nothing
end

# API

function _evaluate_nd!(
  b::BarycentricPmΛBasis{D}, x,
  ω::AbstractMatrix, i, cB,
  ::Val{r}) where {D,r}

  V = eltype(ω)
  λ = _cart_to_bary(x, _get_x_to_λ(b))

  # _evaluate_nd!(::BernsteinBasisOnSimplex) without set_value
  cB[1] = 1
  _downwards_de_Casteljau_nD!(cB,λ,Val(r-1),Val(D))

  @inbounds for (_, bubble_functions) in get_bubbles(b)
    for (w, α, α_id, J, sub_J_ids) in bubble_functions
      ω_w = zero(V)
      for (l, J_sub_Jl_id) in enumerate(sub_J_ids)
        sgnl = _minusone_if_even_else_one(l)
        λ_j = λ[J[l]]
        m_J_l = b.m[J_sub_Jl_id]

        ω_w += flipsign(λ_j,sgnl) * m_J_l
      end

      Bα = cB[α_id]
      if b.flavor === :BMM
        # slow, but since the basis is not well contitioned, using :BMM is discouraged
        Bα /= multinomial(α...)
      end

      ω[i,w] = Bα * ω_w
    end
  end
end

function _gradient_nd!(
  b::BarycentricPmΛBasis{D}, x,
  ∇ω::AbstractMatrix{G}, i, cB,
  ∇B::AbstractMatrix{<:VectorValue{D}},
  s::MVector{D},
  ::Val{r}) where {D,G,r}

  _gradient_nd!(b.scalar_bernstein_basis, x, ∇B, 1, cB, nothing, s, Val(r))

  @inbounds for (_, bubble_functions) in get_bubbles(b)
    for (w, α, _, J, sub_J_ids, sup_α_ids) in bubble_functions
      ∇ω_w = zero(G)

      for (l, J_sub_Jl_id) in enumerate(sub_J_ids)
        sgnl = _minusone_if_even_else_one(l)
        Jl = J[l]
        α_pJl_id = sup_α_ids[Jl]

        ∇Bα_pJl = ∇B[1,α_pJl_id]
        c_α_Jl = (α[Jl]+1) * sgnl / r
        m_J_l = b.m[J_sub_Jl_id]

        ∇ω_w += (c_α_Jl * ∇Bα_pJl) ⊗ m_J_l
      end

      if b.flavor === :BMM
        ∇ω_w /= multinomial(α...)
      end

      ∇ω[i,w] = ∇ω_w
    end
  end
end

function _hessian_nd!(
  b::BarycentricPmΛBasis{D}, x,
  Hω::AbstractMatrix{G}, i, cB,
  ::Nothing,
  HB::AbstractMatrix{<:TensorValue{D,D}},
  s::MMatrix{D,D},
  ::Val{r}) where {D,G,r}

  _hessian_nd!(b.scalar_bernstein_basis, x, HB, 1, cB, nothing, nothing, s, Val(r))

  @inbounds for (_, bubble_functions) in get_bubbles(b)
    for (w, α, _, J, sub_J_ids, sup_α_ids) in bubble_functions
      Hω_w = zero(G)

      for (l, J_sub_Jl_id) in enumerate(sub_J_ids)
        sgnl = _minusone_if_even_else_one(l)
        Jl = J[l]
        α_pJl_id = sup_α_ids[Jl]

        HB_αJl = HB[1,α_pJl_id]
        c_αJl = (α[Jl]+1) * sgnl / r
        m_Jl = b.m[J_sub_Jl_id]

        Hω_w += (c_αJl * HB_αJl) ⊗ m_Jl
      end

      if b.flavor === :BMM
        Hω_w /= multinomial(α...)
      end

      Hω[i,w] = Hω_w
    end
  end
end


#####################################
# BarycentricPΛBasis Implementation #
#####################################

function _generate_or_check_PΛ_indices(r,k,D,DG_style,::Nothing,rot_90)
  identity = objectid( (r,k,D,:P,DG_style,rot_90) )
  bubbles = PΛ_bubbles(r,k,D)
  components = _basis_forms_components(D,k,DG_style,rot_90)
  return BarycentricPΛIndices(identity,bubbles,components)
end

function _generate_or_check_PΛ_indices(r,k,D,DG_style,indices::BarycentricPΛIndices,rot_90)
  _check_PΛ_indices(r,k,D,:P,DG_style,indices,rot_90)
  return indices
end

function _PΛ_F_bubble_functions(r,k,D,F,w)
  N = D + 1
  bubble_functions = BubbleFunction[]
  empty_vec = Int[]
  for α in bernstein_terms(r,D)
    for J in sorted_combinations(N,k)
      j = _minimum_or_one(setdiff(F,J))-1
      if issetequal(_support(α) ∪ J, F) && all(α[1:j] .== 0)
        w += 1
        α_id = bernstein_term_id(α)
        push!(bubble_functions, (w, α, α_id, J, empty_vec, empty_vec))
      end
    end
  end
  bubble_functions
end

"""
    PΛ_bubbles(r,k,D)

Generates the indices caracterizing the basis function of `BarycentricPΛBasis`,
described in the Bernstein bases algorithm Developper notes of the official
documentation, and are used as follows:

    for (F, bubble_functions) in PΛ_bubbles(r,k,D)
      for (w, α, α_id, J) in bubble_functions
        # ...
      end
    end
"""
function PΛ_bubbles(r,k,D)
  bubbles = Bubble[]
  if r == 0
    F = [1:(D+1)...]
    α = zeros(Int,D+1)
    bubble_functions = BubbleFunction[]
    for i in 1:binomial(D,k)
      push!(bubble_functions, (i, α, 1, [], [], [])) # J has no meaning there
    end
    push!(bubbles, (F, bubble_functions))
    return bubbles
  end
  # r > 0
  w=0
  for d in k:D
    for F in sorted_combinations(D+1, d+1; right_to_left=true)
      bubble_functions = _PΛ_F_bubble_functions(r,k,D,F,w)
      isempty(bubble_functions) && continue
      push!(bubbles, (F, bubble_functions))
      w += length(bubble_functions)
    end
  end
  @check w == binomial(r+k,k)*binomial(D+r,D-k)
  bubbles
end

function _compute_PΛ_basis_form_coefficient!(Ψ,r,k,::Val{D},b,vertices,indices,flavor=:AFW) where D
  N = D+1
  Vk = Val(k)
  V = eltype(Ψ)

  iszero(r) && return _order_0_Ψ!(Ψ)

  T = eltype(V)
  α_prec = ntuple(_->-1, N)
  φ_αF = MMatrix{D,N,T}(undef)
  Ψw = Mutable(V)(undef)
  @inbounds for (F, bubble_functions) in indices.bubbles
    for (w, α, _, J) in bubble_functions
      if α ≠ α_prec
        _update_φ_αF!(φ_αF,b,α,F,r,flavor)
        α_prec = α
      end

      for (I_id, I, I_sgn) in indices.components
        Ψw[I_id] = I_sgn * _minor(φ_αF,I,J,Vk)
      end
      Ψ[w] = Ψw
    end
  end
  nothing
end

"""
    _update_φ_αF!(φ_αF, b, α, F, r, flavor)

Set in place the `D`×`N` matrix `φ_αF` the direction 1-forms `φ_αF[:,j] =
φ^{α,F,j}` where

    φ^{α,F,j} = dλʲ - (sⱼ/|s|) Σ_{l∈F} dλˡ,     1 ≤ j ≤ N.

`flavor` selects which multi-index weights the correction term:
- `:AFW` uses `s=α` and `r` = |`α`|,
- `:BMM` uses the support indicator of `α` and its cardinal.
"""
@inline function _update_φ_αF!(φ_αF,b::BernsteinBasisOnSimplex{D},α,F,r,flavor=:AFW) where D
  M = b.x_to_λ
  s = ntuple(j -> α[j], Val(D+1))
  if flavor === :BMM
    s = map(αj -> Int(αj > 0), s) #  s  in paper
    r = sum(s)                    # |s| in paper
  end
  @inbounds for ci in CartesianIndices(φ_αF)
    i, j = ci[1], ci[2]
    mF = sum(M[Fl,i+1] for Fl in F; init=0)
    φ_αF[ci] = M[j,i+1] - s[j]*mF/r
  end
end

function _order_0_Ψ!(Ψ)
  V = eltype(Ψ)
  T = eltype(V)
  for w in eachindex(Ψ)
    Ψ[w] = ntuple( i -> T(i==w), length(V))
  end
  nothing
end


# API

function _evaluate_nd!(
  b::BarycentricPΛBasis{D}, x,
  ω::AbstractMatrix, i, cB,
  ::Val{r}) where {D,r}

  λ = _cart_to_bary(x, _get_x_to_λ(b))

  # _evaluate_nd!(::BernsteinBasisOnSimplex) without set_value
  cB[1] = 1
  _downwards_de_Casteljau_nD!(cB,λ,Val(r),Val(D))

  @inbounds for (_, bubble_functions) in get_bubbles(b)
    for (w, _, α_id) in bubble_functions
      Ψw = b.Ψ[w]
      Bα = cB[α_id]
      ω[i,w] = Bα * Ψw
    end
  end
end

function _gradient_nd!(
  b::BarycentricPΛBasis{D}, x,
  ∇ω::AbstractMatrix, i, cB,
  ∇B::AbstractMatrix{<:VectorValue{D}},
  s::MVector{D},
  ::Val{r}) where {D,r}

  _gradient_nd!(b.scalar_bernstein_basis, x, ∇B, 1, cB, nothing, s, Val(r))

  @inbounds for (_, bubble_functions) in get_bubbles(b)
    for (w, _, α_id) in bubble_functions
      Ψw = b.Ψ[w]
      ∇Bα = ∇B[1,α_id]
      ∇ω[i,w] = ∇Bα ⊗ Ψw
    end
  end
end

function _hessian_nd!(
  b::BarycentricPΛBasis{D}, x,
  Hω::AbstractMatrix, i, cB,
  ::Nothing,
  HB::AbstractMatrix{<:TensorValue{D,D}},
  s::MMatrix{D,D},
  ::Val{r}) where {D,r}

  _hessian_nd!(b.scalar_bernstein_basis, x, HB, 1, cB, nothing, nothing, s, Val(r))

  @inbounds for (_, bubble_functions) in get_bubbles(b)
    for (w, _, α_id) in bubble_functions
      Ψw = b.Ψ[w]
      HBα = HB[1,α_id]
      Hω[i,w] = HBα ⊗ Ψw
    end
  end
end


################################################################
# Combination, Bernstein term and Barycentric PΛ bases helpers #
################################################################

"""
    _complement(I, D)

Given a k-combination `I` of elements of `1:D`, returns the unique (`D`-k)
combination of `1:D` "`Icomp`" such that `I ∪ Icomp ⊇ 1:D`.
"""
function _complement(combi, D)
  k = length(combi)
  combi_comp = Vector{Int}(undef, D-k)
  curr_perm, curr_comp = 1, 1
  for i in 1:D
    if curr_perm ≤ k && combi[curr_perm] == i
      curr_perm += 1
    else
      combi_comp[curr_comp] = i
      curr_comp += 1
    end
  end
  combi_comp
end

"""
    _combination_sign(I)

Given a combination `I`, returns the sign of the permutation resulting from
the concatenation of `I` and its complement [`_complement(I,D)`](@ref _complement).
"""
function _combination_sign(combi)
  @check issorted(combi)
  i, k, acc, delta = 1, 1, 0, 0
  while k <= length(combi)
    if combi[k] == i
      acc += delta
      k += 1
    else
      delta += 1
    end
    i += 1
  end
  return iseven(acc) ? 1 : -1
end

"""
    _sub_combinations_ids(J, D)

Return a vector containing the `combination_index` of the `k` different
combinations `J\\J[i]` of 1:`D` for 1 ≤ i ≤ `k`, where `k=length(J)`.

`D` is the ambient dimension the indices are taken in, that is the one `J`
itself is a combination of — not the dimension of the space the forms live in.
"""
function _sub_combinations_ids(combi, D)
  k = length(combi)
  sub_combi = MVector{k-1,Int}(undef)
  sub_combi_ids = Vector{Int}(undef, k)
  for i in 1:k
    sub_combi .= ntuple(j -> combi[j + Int(j≥i)],k-1)
    sub_combi_id = combination_index(sub_combi, D)
    sub_combi_ids[i] = sub_combi_id
  end
  sub_combi_ids
end

"""
    _sup_multi_indices(α)

Given `α` a Bernstein term of length N, return the [`bernstein_term_id `](@ref)
of the N terms `α`+eᵢ for 1 ≤ i ≤ N in a Vector (in order of i increasing).
"""
function _sup_multi_indices(α)
  N = length(α)
  sup_α = MVector{N,Int}(undef)
  sup_α_ids = Vector{Int}(undef, N)
  for i in 1:N
    sup_α .=  ntuple(k -> α[k]+Int(k==i), N)
    sup_α_id = bernstein_term_id(sup_α)
    sup_α_ids[i] = sup_α_id
  end
  return sup_α_ids
end

"""
    _support(α)

Given a bernstein multi-index `α`, returns the set of indices `i` such that `αᵢ`>0.
"""
function _support(α)
  s = Int[]
  for (i,αi) in enumerate(α)
    if αi > 0
      push!(s, i)
    end
  end
  s
end

"""
    _minor(M,I,J,::Val{k})

Computes the minor (determinant of sub-matrix) of the matrix M where the rows of
indices i∈`I` and column of indics j∈`J` are kept. `k` is the length of both `I`
and `J`.
"""
function _minor(M,I,J,::Val{k}) where k
  @check length(I) == length(J)
  @check I ⊆ axes(M)[1]
  @check J ⊆ axes(M)[2]

  T = eltype(M)
  m = MMatrix{k,k,T,k*k}(undef)
  for (i, Ii) in enumerate(take(I,k))
    for (j, Jj) in enumerate(take(J,k))
      @inbounds m[i,j] = M[Ii,Jj]
    end
  end
  det(m)
end

@propagate_inbounds function _minusone_if_even_else_one(i)
  iseven(i) ? -1 : 1
end

@propagate_inbounds function _findfirst_val_or_zero(pred, start, stop)
  r = findfirst(pred,start:stop)
  return isnothing(r) ? 0 : r+start-1
end

@propagate_inbounds function _minimum_or_one(s)
  maxint = typemax(Int)
  j = minimum(s, init=maxint)
  j = (j==maxint) ? 1 : j
end


######################################################
# Change of basis with respect to vertex relabelling #
######################################################

# Change of basis induced on the rotating bases by a vertex relabeling
# (rotation) π : ξ → λ, λ = π(ξ). This file implements the closed-form index
# calculus, for form order k=1.

###########################
# Vertex/multi-index maps #
###########################

"""
    rotate_face_set(F::Vector{Int}, π::Vector{Int}) -> Vector{Int}

π(F) as a sorted vertex-set key, `sort(π[F])`. The rotating bases never track
face orientation — their bubbles are built from `combinations`, which already
returns canonical sorted vertex sets — so sorting the rotated image loses
nothing this module relies on. Do not reuse this for orientation-sensitive
code, where a face's vertex order encodes its orientation.
"""
rotate_face_set(F::Vector{Int}, π::Vector{Int}) = sort(π[F])

"""
    rotate_multiindex(α, π) -> Vector{Int}

π(α), per `π(α)_i = α_{π⁻¹(i)}`. The only inverse used anywhere in this file:
the exact combinatorial `invperm`, never a numerical/matrix inverse. To apply
π⁻¹ instead, call this (or anything downstream of it) with `invperm(π)`.
"""
rotate_multiindex(α::AbstractVector{Int}, π::Vector{Int}) = α[invperm(π)]

#################################
# Bubble (F,k,α) ↔ index lookup #
#################################

_bubble_entry_type(::BarycentricPΛBasis)  = Tuple{Vector{Int},Int,Vector{Int}}
_bubble_entry_type(::BarycentricPmΛBasis) = Tuple{Vector{Int},Tuple{Int,Int},Vector{Int}}

# A Barycentric bubble function stores its direction form as the index set J.
# For 1-forms that is the single vertex the untrimmed closed form calls k, resp.
# the pair (e1,e2) spanning the Whitney form of the trimmed one.
_bubble_key(::BarycentricPΛBasis,  J) = J[1]
_bubble_key(::BarycentricPmΛBasis, J) = (J[1], J[2])

"""
    bubble_entries(b) -> Vector{Tuple{Vector{Int},kT,Vector{Int}}}

`(F,k,α)` for each basis function `w`, indexed by `w`. `k` is a single vertex
for the untrimmed basis and a pair `(e1,e2)` for the trimmed one.

The entries depend on the bubble index set alone, hence are the same for both
flavors of a given `(r,k,D)`.
"""
function bubble_entries(b::_BaryPΛBasis)
  @check isone(b.k) "The rotation API is only defined for 1-forms, got k=$(b.k)"
  entries = Vector{_bubble_entry_type(b)}(undef, length(b))
  for (F, bubble_functions) in get_bubbles(b), (w, α, _, J) in bubble_functions
    entries[w] = (F, _bubble_key(b, J), α)
  end
  entries
end

"""
    bubble_index(b) -> Dict{entry,Int}

Inverse of [`bubble_entries`](@ref): `(F,k,α) → w`.
"""
bubble_index(b::_BaryPΛBasis) = Dict(e => w for (w, e) in enumerate(bubble_entries(b)))

######################
# Basis-level rotate #
######################

"""
    rotate_basis_function(b, w::Int, π::Vector{Int}) -> Vector{Tuple{Float64,Int}}

Pullback under π⁻¹ of the `w`-th basis function of `b`, expressed as a list of
`(coefficient, target index)` pairs in the same basis `b`, now read with the
relabeled vertices λ = π(ξ). Implements the two cases of the pullback theorems:
a single term, of coefficient +1 untrimmed and ±ε trimmed; or the filter-hit
expansion, of |F|−1 terms of coefficient −1 untrimmed and two terms of
coefficient ±ε weighted by [`_trimmed_hit_weight`](@ref) trimmed.

For repeated calls (e.g. assembling [`rotation_change_of_basis`](@ref)),
precompute `entries = bubble_entries(b)` and `idx = bubble_index(b)` once and
call the internal
`Gridap.Polynomials._rotate_basis_function(entries, idx, w, π, b.flavor)`.
"""
function rotate_basis_function(b::_BaryPΛBasis, w::Int, π::Vector{Int})
  entries = bubble_entries(b)
  idx     = bubble_index(b)
  _rotate_basis_function(entries, idx, w, π, b.flavor)
end

# Full basis

# Untrimmed closed form: single term (+1) unless supp(α) = F and
# π(k) = min(π(F)), in which case the resummation identity gives |F|−1 terms
# with coefficient −1. Every term carries the same multi-index π(α), so the
# scalar normalisation of the flavor factors out and the law is the same for
# both, whence the ignored flavor argument.
function _rotate_basis_function(
  entries::Vector{Tuple{Vector{Int},Int,Vector{Int}}}, idx, w::Int, π::Vector{Int}, ::Symbol)
  F, k, α = entries[w]
  πF = rotate_face_set(F, π)
  πk = π[k]
  πα = rotate_multiindex(α, π)
  full_support = α[k] > 0   # [s(α)] == F  ⟺  k ∈ [s(α)]  ⟺  α[k] > 0
  if full_support && πk == minimum(πF)
    [(-1.0, idx[(πF, vi, πα)]) for vi in πF if vi != πk]
  else
    [(1.0, idx[(πF, πk, πα)])]
  end
end

# Trimmed basis

"""
    trimmed_pair_sign(e1, e2) -> Float64

ε(e1,e2) := 2·[e1<e2] − 1.
"""
trimmed_pair_sign(e1::Int, e2::Int) = e1 < e2 ? 1.0 : -1.0

"""
    trimmed_pair_sort(e1, e2) -> (Int,Int)

e↑ := (min(e1,e2), max(e1,e2)).
"""
trimmed_pair_sort(e1::Int, e2::Int) = minmax(e1, e2)

"""
    _trimmed_hit_weight(flavor, β, m, j) -> Float64

Weight of the hit term whose multi-index is the shift ρ(`m`,`j`)∘`β`.

The two hit terms are shifts of `β`, so the scalar normalisation of the flavor
does not factor out of the expansion: it survives as the ratio of the
normalisations of `β` and of ρ(`m`,`j`)∘`β`. For the Bernstein polynomials
Bᵦ = multinomial(β) λ^β of `:AFW` that ratio is (βⱼ+1)/βₘ; the bare monomials
λ^β of `:BMM` are unnormalised and give 1.

`β`ₘ is positive on every hit, so the weight is well defined.
"""
function _trimmed_hit_weight(flavor::Symbol, β::Vector{Int}, m::Int, j::Int)
  flavor === :AFW || return 1.0
  (β[j] + 1) / β[m]
end

# Trimmed closed form: single signed term (ε) when the rotated sorted pair is
# anchored (min(π(e)) = min(π(F))); otherwise the two-term shift expansion
#   ε · ( c₁ w(λ;π(F),(m,eπ2),ρ(m,eπ1)∘π(α)) − c₂ w(λ;π(F),(m,eπ1),ρ(m,eπ2)∘π(α)) )
# where ρ(m,eπ1)∘π(α) = π(α) - 𝟙_m + 𝟙_eπ1. Which of the two cases applies does
# not depend on α, since ϕ does not; the weights cᵢ do, unless they are trivial.
function _rotate_basis_function(
  entries::Vector{Tuple{Vector{Int},Tuple{Int,Int},Vector{Int}}}, idx, w::Int, π::Vector{Int},
  flavor::Symbol)

  F, e, α  = entries[w]
  e1, e2   = e
  πF       = rotate_face_set(F, π)
  πe1,πe2  = π[e1], π[e2]
  πα       = rotate_multiindex(α, π)
  ε        = trimmed_pair_sign(πe1, πe2)
  eπ1,eπ2  = trimmed_pair_sort(πe1, πe2)
  m      = minimum(πF)

  if m != eπ1   # hit: min(π(e)) ≠ min(π(F))
    # m < eπ1 ⟹ m ∉ {eπ1,eπ2} ⟹ m ∈ supp(π(α)) by the covering condition
    @assert πα[m] > 0 "invalid trimmed entry: hit at α with α[min π(F)] = 0"
    α1 = copy(πα); α1[m] -= 1; α1[eπ1] += 1   # ρ(m,eπ1)∘π(α)
    α2 = copy(πα); α2[m] -= 1; α2[eπ2] += 1   # ρ(m,eπ2)∘π(α)
    c1 = ε * _trimmed_hit_weight(flavor, πα, m, eπ1)
    c2 = ε * _trimmed_hit_weight(flavor, πα, m, eπ2)
    [(c1, idx[(πF, (m,eπ2), α1)]), (-c2, idx[(πF, (m,eπ1), α2)])]
  else
    [(ε, idx[(πF, (eπ1,eπ2), πα)])]
  end
end

#####################
# Cached rotations  #
#####################

"""
    RotationCache(b)

Precomputes the bubble entry table and its index once, and memoises, per
permutation `π`, the signed index map of the rotation:
[`rotation_map`](@ref)`(rc, π)[w]` is the `Vector{Tuple{Float64,Int}}` of
`(coefficient, target index)` pairs of `rotate_basis_function(b, w, π)`.
"""
struct RotationCache{B<:_BaryPΛBasis,E}
  basis   :: B
  entries :: Vector{E}
  idx     :: Dict{E,Int}
  maps    :: Dict{Vector{Int},Vector{Vector{Tuple{Float64,Int}}}}
end

function RotationCache(b::_BaryPΛBasis)
  entries = bubble_entries(b)
  idx     = Dict(e => w for (w, e) in enumerate(entries))
  RotationCache(b, entries, idx,
                Dict{Vector{Int},Vector{Vector{Tuple{Float64,Int}}}}())
end

"""
    rotation_map(rc::RotationCache, π::Vector{Int}) -> Vector{Vector{Tuple{Float64,Int}}}

The signed index map of the rotation `π`, one row per basis function, computed
on first request and memoised in `rc`. Rows alias the cache; do not mutate.
"""
function rotation_map(rc::RotationCache, π::Vector{Int})
  m = get(rc.maps, π, nothing)
  m === nothing || return m
  m = [_rotate_basis_function(rc.entries, rc.idx, w, π, rc.basis.flavor)
       for w in 1:length(rc.entries)]
  rc.maps[copy(π)] = m
  m
end

"""
    rotation_change_of_basis(b, π::Vector{Int}) -> Matrix{Float64}

Dense change-of-basis matrix `C` such that the `w`-th basis function of `b`,
pulled back under π⁻¹, equals `∑_w′ C[w,w′] · (w′-th basis function of b, read
with λ = π(ξ))`.
To push forward by π⁻¹ instead, call this with `invperm(π)`.
"""
function rotation_change_of_basis(b::_BaryPΛBasis, π::Vector{Int})
  n = length(b)
  entries = bubble_entries(b)
  idx     = bubble_index(b)
  C = zeros(Float64, n, n)
  for w in 1:n
    for (c, w′) in _rotate_basis_function(entries, idx, w, π, b.flavor)
      C[w, w′] += c
    end
  end
  C
end

# ─────────────────────────────────────────────────────────────────────────────
# Change of basis of the "virtually sorted" cell at a vertex permutation π
# ─────────────────────────────────────────────────────────────────────────────
#
# CONVENTION (pinned empirically over all relative vertex orderings of two-
# triangle and two-tet meshes — the competing candidates C(π)ᵀ, C(invperm(π))
# and every un-relabelled variant fail the tangential jump / interpolation
# round-trip tests at O(1)):
#
# π maps sorted position → local index.  The virtually sorted geometric map is
# F̃ = F ∘ A⁻¹ with A = A_{invperm(π)} (reference automorphism
# V_j ↦ V_{invperm(π)[j]}), hence the conforming basis is
#
#   φ̃_μ = (F̃⁻¹)^* ŵ_μ = Σ_ν C(π)[μ,ν] · (F⁻¹)^* ŵ_ν,
#
# with C = rotation_change_of_basis(b, π).
#
# RELABELLING: φ̃_μ is supported on the LOCAL face π(F(μ)), while the conformity
# machinery glues local index μ by the local face F(μ).  The shape function
# stored at μ must therefore be φ̃_{s(μ)}, with s the face-wise order-preserving
# reindexing sending the i-th bubble of face F to the i-th bubble of
# sort(invperm(π)(F)).  Every cell adjacent to a face then enumerates that
# face's functions in the bubble order of its sorted global vertex ids — which
# is what makes the identity face-own-dof permutations correct for every pindex.
#
# In the linear_combination convention (out[j] = Σ_i values[i,j]·in[i]):
#
#   M[i,j]    = C(π)[s(j), i]           (basis side)
#   Minv[i,j] = C(invperm(π))[i, s(j)]  (dof side, restores duality)
#
# where C(π)·C(invperm(π)) = I.
function compute_pλ_change(rc, π)
  invπ = invperm(π)
  n    = length(rc.entries)

  # s(μ): face-wise order-preserving reindexing local entry → virtual entry,
  # mapping the i-th bubble of face F to the i-th bubble of sort(invperm(π)(F)).
  face_to_ws = Dict(F => [bf[1] for bf in bfs] for (F, bfs) in get_bubbles(rc.basis))
  s = Vector{Int}(undef, n)
  for (F, ws) in face_to_ws
    wsG = face_to_ws[sort(invπ[F])]
    for i in eachindex(ws)
      s[ws[i]] = wsG[i]
    end
  end
  sinv = invperm(s)

  M = zeros(Float64, n, n)
  rows = rotation_map(rc, π)
  for μ in 1:n, (c, w′) in rows[s[μ]]
    M[w′, μ] += c
  end

  Minv = zeros(Float64, n, n)
  rows_inv = rotation_map(rc, invπ)
  for w in 1:n, (c, w′) in rows_inv[w]
    Minv[w, sinv[w′]] += c
  end

  return M, Minv
end

