name: Benchmarks

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target branch'
        required: true
        type: string
      base:
        description: 'Base branch'
        required: true
        default: 'master'
        type: string

jobs:
  benchmark:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        version:
          - '1.10'
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - run: |
          git fetch --tags
          git branch --create-reflog main origin/main
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v4
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
      - name: Install Gridap in main environment
        run: julia -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Install dependencies
        run: julia --project=benchmark/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Run benchmarks
        run: julia --project=benchmark/ --color=yes benchmark/run_benchmarks.jl
        env:
          BM_BASE: ${{ github.event.inputs.base }}
          BM_TARGET: ${{ github.event.inputs.target }}
      - uses: actions/upload-artifact@v4
        with:
          name: benchmarks
          path: benchmark/benchmark_results.md